version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - "1881:1881"
    links:
      - db
    volumes:
      - .:/app
    command: tail -f /dev/null
  db:
    image: mdillon/postgis:10
    restart: always
    environment:
      POSTGRES_USER: discount
      POSTGRES_PASSWORD: discount
      POSTGRES_DB: discount
    ports:
      - '5430:5432'
    volumes:
      - ./.data/dbpgdata:/var/lib/postgresql/data




