# Generated by Django 2.2.4 on 2019-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
