# Generated by Django 2.2.4 on 2019-08-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20190820_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dealer',
            new_name='dealer_id',
        ),
    ]
