# Generated by Django 2.2.4 on 2019-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0002_auto_20190820_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
