# Generated by Django 2.2.4 on 2019-08-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0004_auto_20190820_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='name',
            new_name='dealer_name',
        ),
    ]
