# Generated by Django 2.2.4 on 2019-08-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0005_auto_20190820_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='dealer_name',
            new_name='name',
        ),
    ]
