# Generated by Django 2.2.4 on 2019-08-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('working_area', models.CharField(max_length=30)),
                ('establish_year', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
