# Generated by Django 2.2.4 on 2019-08-20 14:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20190820_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(41.0606 28.9946)', srid=4326),
        ),
    ]
